[package]
name = "editor_app"
edition = "2021"

[[bin]]
name = "rme-rs"
path = "src/main.rs"

[dependencies]
editor_core = { path = "../../crates/editor_core" }
editor_ui   = { path = "../../crates/editor_ui" }
egui        = { workspace = true }
eframe      = { workspace = true, default-features = false, features = ["wgpu", "default_fonts"] }
egui_dock   = { workspace = true }
env_logger  = "0.11.11"
