[package]
name = "editor_app"
edition = "2021"

[[bin]]
name = "rme-rs"
path = "src/main.rs"

[dependencies]
editor_core   = { path = "../editor_core" }
editor_ui     = { path = "../editor_ui" }
editor_render = { path = "../editor_render" }
editor_formats = { path = "../editor_formats" }
egui          = { workspace = true }
eframe        = { workspace = true, features = ["wgpu"] }
egui_dock     = { workspace = true }
env_logger    = "0.11"