[package]
name = "editor_render"
version = "0.1.0"
edition = "2024"

[dependencies]
editor_core = { path = "../editor_core" }
wgpu       = { workspace = true }
bytemuck   = { workspace = true }
egui       = { workspace = true }
egui-wgpu  = { workspace = true }
ahash      = { workspace = true }
editor_formats = { version = "0.1.0", path = "../editor_formats" }

[dev-dependencies]
pollster = "0.4"
png = "0.17"
